### ISSUE TITLE
Create UI for print vehicle details 

### ISSUE THREAD

**Issue by Akib-Vijapura** [Akib-Vijapura/parking-system#9]

**Comment by r00tshaim** [comment]
https://gist.github.com/andrewlimaza/490a69417d9fe2df3f668195a7661605

**Comment by r00tshaim** [comment]
https://stackoverflow.com/questions/468881/print-div-id-printarea-div-only

**Comment by r00tshaim** [comment]
Sending query params to next page -> https://stackoverflow.com/questions/55182529/next-js-router-push-with-state
